#include "main.h"
#include "project-name.elf.p"
#include "stm32f4xx_hal.h"
#include "stm32f4xx_hal_uart.h"
#include "uart_driver.h"
#include <stm32f411xe.h>
// UART handle
UART_HandleTypeDef huart2;

// Buffer to hold received data
uint8_t Rx_data[2];

// Function prototypes
void SystemClock_Config (void);
static void MX_GPIO_Init (void);
static void MX_USART2_UART_Init (void);
void HAL_UART_RxCpltCallback (UART_HandleTypeDef *huart);

int
main (void)
{
    // Initialize the HAL Library
    HAL_Init ();

    // Configure the system clock
    SystemClock_Config ();

    // Initialize all configured peripherals
    MX_GPIO_Init ();
    MX_USART2_UART_Init ();

    // Start UART in receive interrupt mode
    HAL_UART_Receive_IT (&huart2, Rx_data, 1);

    // Main loop
    while (1)
        {
            // Transmit a string
            uint8_t msg[] = "Hello UART\r\n";
            HAL_UART_Transmit (&huart2, msg, sizeof (msg) - 1, HAL_MAX_DELAY);

            // Delay
            HAL_Delay (1000);
        }
}

void
SystemClock_Config (void)
{
    // Configure system clock (generated by CubeMX)
    // ...
}

static void
MX_GPIO_Init (void)
{
    // Initialize GPIO (generated by CubeMX)
    // ...
}

static void
MX_USART2_UART_Init (void)
{
    // Initialize UART2 (generated by CubeMX)
    huart2.Instance = USART2;
    huart2.Init.BaudRate = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits = UART_STOPBITS_1;
    huart2.Init.Parity = UART_PARITY_NONE;
    huart2.Init.Mode = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init (&huart2) != HAL_OK)
        {
            Error_Handler ();
        }
}

void
HAL_UART_RxCpltCallback (UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART2)
        {
            // Echo received data back
            HAL_UART_Transmit (&huart2, Rx_data, 1, 10);

            // Restart UART receive interrupt mode
            HAL_UART_Receive_IT (&huart2, Rx_data, 1);
        }
}

void
Error_Handler (void)
{
    // User can add his own implementation to report the HAL error return state
    while (1)
        {
        }
}
